version: '3'

services:
  apache:
    image: rafaelcgstz/magento2
    # build: .
    ports:
      - "9001:9001" # xdebug
    volumes:
      - /opt/atlassian/pipelines/agent/build:/var/www
      - /opt/atlassian/pipelines/agent/build/.composer:/var/www/.composer
      - /opt/atlassian/pipelines/agent/build/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
#    networks:
#      - dbbridge

  db:
    image: mariadb
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
#    networks:
#      - dbbridge
  
  redis:
    image: redis
    ports:
      - 6379

  redis-session:
    image: redis
    ports:
      - 6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
      
#networks:
#  dbbridge:
#    name: dbbridge
